---
title: "WordRec Experiment"
author: "A. Fourtassi & M. Frank"
date: "January 13, 2017"
output:
  html_document:
    number_sections: yes
    toc: yes
---

Libraries.

```{r}
library(readr)
library(dplyr)
library(tidyr)
library(ggplot2)
library(langcog)
theme_set(theme_bw())
```


Data. 

```{r}

d_word <- read_delim("pilot3_kids.txt", delim = " ") %>%
  filter(type == "Test") %>%
  filter(age != 6)
  
```


Process word learning data

```{r}
#Average

data <- d_word %>%
  mutate(iscorrect=ifelse(answer==correct, 1, 0)) %>%
  group_by(sound_dist, concept_dist) %>%
  multi_boot_standard(col = "iscorrect")

data$sound_dist <- factor(data$sound_dist, levels = c('similar','different', 'maximal'))


ggplot(data, 
       aes(x = sound_dist, y = mean, col = factor(concept_dist))) +
       #aes(x = concept_dist, y = mean)) + 
  geom_pointrange(aes(ymin = summary_ci_lower, ymax = summary_ci_upper), 
                  position = position_dodge(width = .1)) + 
  geom_line(lty = 2) + 
  xlab("Aud distance") +ylab("% Accurate")+
  scale_colour_discrete(name="Vis Dist")+
theme(legend.title = element_text(size=8)) #+  facet_grid(. ~ item)

```


Process discrimianation data

```{r}
concept <- d_discrim %>%
  filter(condition == 'concept') %>%
  group_by( concept_dist) %>%
  multi_boot_standard(col = "answer") #%>%
  #rename(concept_dist = conceptOrd,
      #   semDist=mean)


sound <- d_discrim %>% 
  filter(condition == 'sound') %>%
  group_by(sound_dist, sameDiff) %>%
  multi_boot_standard(col = "answer") #%>%
 # mutate(contrast= paste(phone1, "/", phone2, sep="")) %>%
  #select(-phone1) %>%
  #select(-phone2)

```

plot discrimination data

```{r}
plot_concept  <- ggplot(concept, aes(x = concept_dist, y= mean)) +
  geom_pointrange(aes(ymin = ci_lower, ymax = ci_upper), 
                  position = position_dodge(width = .03), size=0.5) + 
 
 xlab("distance") +ylab("% different")+ theme_bw()  

plot_concept

#sound$distance <- factor(sound$distance, levels = c('pl','in','ar1','ar2'))

plot_sound  <- ggplot(sound, aes(x = sound_dist, y= mean, col=sameDiff)) +
  geom_pointrange(aes(ymin = ci_lower, ymax = ci_upper), 
                  position = position_dodge(width = .03), size=0.5) +
 
 xlab("distance") +ylab("% different")+ theme_bw() 

plot_sound
```